[package]
name = "cmpr-cli"
description = "Command-line front-end for the cmpr archiver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cmpr"
path = "src/main.rs"

[dependencies]
cmpr-codecs.workspace = true
anyhow.workspace = true
clap.workspace = true

[lints]
workspace = true
